name = "siret-enricher"
main = "worker.mjs"
compatibility_date = "2025-07-01"

[vars]

[[d1_databases]]
binding = "DB"
database_name = "siret_enricher"
database_id = ""

[triggers]
crons = ["*/2 * * * *"]

[observability]
enabled = true
